title: Yixiao Chen's Homepage
page-top-title: Yixiao Chen
top-section-bg-text: Computer Science
home-subtitle: Yixiao Chen&ensp;|&ensp;陈奕骁
copyright-text: '&copy; Yixiao Chen 2025-2025. All Rights Reserved.'
